import {
  getInstructionOutputPath,
  getInstructionTargets,
  type CodeWardConfig,
  type InstructionTarget,
  type RepoMap
} from "@codeward/core";

export interface InstructionFile {
  contents: string;
  path: string;
  target: InstructionTarget;
}

export function generateAgentsMd(repoMap: RepoMap, config: CodeWardConfig): string {
  const lines = [
    `# ${repoMap.projectName} Agent Instructions`,
    "",
    "This file was generated by CodeWard. Keep it specific to this repository and update it when architecture or validation rules change.",
    "",
    "## Project Context",
    "",
    `- Package manager: ${repoMap.packageManager}`,
    `- Frameworks: ${formatList(repoMap.frameworks)}`,
    `- Languages: ${formatList(repoMap.languages)}`,
    `- Validation commands: ${formatCommands(repoMap.scripts, config.validation.commands)}`,
    "",
    "## Hard Rules",
    "",
    "- Read the relevant files before editing.",
    "- Keep changes focused on the requested task.",
    "- Prefer existing patterns and helpers over new abstractions.",
    "- Do not commit secrets, tokens, cookies, private certificates, or production data.",
    "- Do not disable tests, type checks, authorization, validation, or error handling to make a check pass.",
    "- Report exact commands run and their results.",
    "",
    ...frameworkRules(repoMap),
    "## Risky Areas",
    "",
    ...formatPathBullets(repoMap.paths.risky, "No high-risk paths were detected yet."),
    "",
    "## Environment Variables",
    "",
    ...formatEnvSection(repoMap),
    "",
    "## Expected Verification",
    "",
    ...formatValidation(config.validation.commands, repoMap.scripts),
    ""
  ];

  if (config.agents.style === "strict") {
    lines.push(
      "## Strict Mode",
      "",
      "- Ask before changing public APIs, database migrations, authentication, authorization, billing, or CI release behavior.",
      "- If a meaningful check fails, fix that failing check only or report the exact blocker.",
      ""
    );
  }

  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trim()}\n`;
}

export function generateCopilotInstructionsMd(repoMap: RepoMap, config: CodeWardConfig): string {
  const lines = [
    `# ${repoMap.projectName} Copilot Instructions`,
    "",
    "This file was generated by CodeWard for GitHub Copilot code review and AI-assisted engineering workflows.",
    "",
    "## Review Focus",
    "",
    "- Prioritize production risks over style preferences.",
    "- Check whether changes follow this repository's architecture, validation commands, and risky path policy.",
    "- Flag authorization, environment, dependency, migration, and missing-test risks clearly.",
    "- Do not suggest unrelated refactors when a focused fix is enough.",
    "",
    "## Project Context",
    "",
    `- Package manager: ${repoMap.packageManager}`,
    `- Frameworks: ${formatList(repoMap.frameworks)}`,
    `- Languages: ${formatList(repoMap.languages)}`,
    `- Validation commands: ${formatCommands(repoMap.scripts, config.validation.commands)}`,
    "",
    ...frameworkRules(repoMap),
    "## Risky Areas",
    "",
    ...formatPathBullets(repoMap.paths.risky, "No high-risk paths were detected yet."),
    "",
    "## Expected Verification",
    "",
    ...formatValidation(config.validation.commands, repoMap.scripts),
    ""
  ];

  if (config.agents.style === "strict") {
    lines.push(
      "## Strict Mode",
      "",
      "- Request human review for public API, database migration, authentication, authorization, billing, or CI release changes.",
      "- Treat failed validation as a blocker unless the pull request explains a scoped exception.",
      ""
    );
  }

  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trim()}\n`;
}

export function generateInstructionFiles(repoMap: RepoMap, config: CodeWardConfig): InstructionFile[] {
  return getInstructionTargets(config).map((target) => ({
    contents: target === "agents" ? generateAgentsMd(repoMap, config) : generateCopilotInstructionsMd(repoMap, config),
    path: getInstructionOutputPath(config, target),
    target
  }));
}

function frameworkRules(repoMap: RepoMap): string[] {
  const rules = ["## Repository-Specific Rules", ""];

  if (repoMap.frameworks.includes("nextjs")) {
    rules.push(
      "- Next.js server actions and API routes must validate the session before mutating data.",
      "- Do not import server-only modules into client components.",
      "- Keep loading, empty, error, and unauthorized UI states intact when changing user flows."
    );
  }

  if (repoMap.frameworks.includes("prisma")) {
    rules.push(
      "- Prisma access must stay on the server side.",
      "- Mutations touching tenant-owned data must check resource ownership.",
      "- Database migrations require focused review and rollback notes."
    );
  }

  if (repoMap.frameworks.includes("typescript")) {
    rules.push(
      "- Avoid `any`; prefer explicit types or `unknown` plus validation at boundaries.",
      "- Do not hide errors with empty `catch` blocks."
    );
  }

  if (repoMap.frameworks.includes("react")) {
    rules.push(
      "- Preserve keyboard access and semantic HTML for interactive UI.",
      "- Keep state ownership clear; do not introduce a new state library without an explicit reason."
    );
  }

  if (rules.length === 2) {
    rules.push("- Follow the existing project structure and validation scripts detected by CodeWard.");
  }

  rules.push("");
  return rules;
}

function formatList(values: string[]): string {
  return values.length ? values.join(", ") : "not detected";
}

function formatCommands(scripts: Record<string, string>, configured: Record<string, string>): string {
  const commands = Object.values(configured).length ? Object.values(configured) : inferCommands(scripts);
  return commands.length ? commands.join("; ") : "not detected";
}

function formatPathBullets(paths: string[], fallback: string): string[] {
  if (!paths.length) {
    return [`- ${fallback}`];
  }
  return paths.slice(0, 20).map((file) => `- \`${file}\``);
}

function formatEnvSection(repoMap: RepoMap): string[] {
  if (!repoMap.env.used.length) {
    return ["- No environment variable usage was detected."];
  }

  const lines = [`- Used by code: ${repoMap.env.used.map((name) => `\`${name}\``).join(", ")}`];
  if (repoMap.env.missingFromExample.length) {
    lines.push(
      `- Missing from \`.env.example\`: ${repoMap.env.missingFromExample.map((name) => `\`${name}\``).join(", ")}`
    );
  } else {
    lines.push("- `.env.example` covers the detected environment variables.");
  }
  return lines;
}

function formatValidation(configured: Record<string, string>, scripts: Record<string, string>): string[] {
  const commands = Object.entries(configured).length
    ? Object.entries(configured)
    : inferCommandEntries(scripts);

  if (!commands.length) {
    return ["- No validation commands were detected. Add lint, typecheck, test, and build scripts when available."];
  }

  return commands.map(([name, command]) => `- ${name}: \`${command}\``);
}

function inferCommands(scripts: Record<string, string>): string[] {
  return inferCommandEntries(scripts).map(([, command]) => command);
}

function inferCommandEntries(scripts: Record<string, string>): Array<[string, string]> {
  const commands: Array<[string, string]> = [];
  for (const name of ["lint", "typecheck", "test", "build"]) {
    if (scripts[name]) {
      commands.push([name, `pnpm ${name}`]);
    }
  }
  return commands;
}
